//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public long ISBN { get; set; }
        public string BookName { get; set; }
        public string Authors { get; set; }
        public int PublisherID { get; set; }
        public Nullable<int> YearOfPublication { get; set; }
    
        public virtual Publishers Publishers { get; set; }
    }
}
